# docker-compose.yml — ajoute ça temporairement en dev
services:
  portfolio:
    build: .
    container_name: portfolio
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro   # ← montage direct
    networks:
      - proxy

networks:
  proxy: